spring:
  application:
    name: core

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history

server:
  port: 1111

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

oauth2:
  client:
    google:
      client-id: ${OAUTH_GOOGLE_CLIENT_ID}
      client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    github:
      client-id: ${OAUTH_GITHUB_CLIENT_ID}
      client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
  redirect-uri-base: ${OAUTH_REDIRECT_URI_BASE:http://localhost:1111}

core:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:86400000}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
