services:
  postgres:
    image: postgres:17-alpine
    container_name: dpmsn_postgres
    restart: always
    env_file:
      - ./db/.env.development
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - localnet

  pgweb:
    image: sosedoff/pgweb
    container_name: dpmsn_pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://dpmsn:dpmsn@postgres:5432/dpmsn_db?sslmode=disable
    depends_on:
      - postgres
    networks:
      - localnet

volumes:
  db:

networks:
  localnet:
    driver: bridge
